### ISSUE TITLE
[BUG] Failed to switch from public cloud to China cloud with pbicli cloud set --name China

### ISSUE THREAD

**Issue by kai-w-wang** [powerbi-cli/powerbi-cli#37]
**Versions**: 1.3.0

-   **pbicli version**: 1.3.0
-   **nodejs version**: v16.13.1
-   **os name/version**: Windows 11

**Describe the bug**
Failed to switch from public cloud to China cloud with pbicli cloud set --name China --verbose

**To Reproduce**
1. Switch cloud:
pbicli cloud set --name China --verbose
Set configured cloud to China
2. List active cloud
pbicli cloud list --verbose
List configured cloud
cloud: public
4. check %userprofile%\\.powerbi-cli\config.json
type %userprofile%\\.powerbi-cli\config.json
{"defaults":{"cloud":"China"},"core":{"cloud":"public"}}

**Expected behavior**
Switch to China version Power BI cloud

**Comment by liprec** [comment]
Thanks for the feedback and I will take a look what is happing and why it is not working as expected.

**Comment by liprec** [comment]
Hi @kwkaiwang,

I just pushed a new version (1.3.1) that hopefully fixes the problem you encounter. Problem is that I cannot validate it myself as I do not have access to the Azure China cloud.
Can you please check if you can set the cloud to `China` and login successfully?
And if not, please let me know so we can take a look at it together.

Thanks, Jan Pieter

**Comment by kai-w-wang** [comment]
I can switch cloud to China this time, but still fail at login:

```
pbicli login
The default web browser has been opened at https://login.chinacloudapi.cn/common/oauth2/v2.0/authorize. Please continue the login in the web browser.
If no web browser is available or if the web browser fails to open, use device code flow
with 'pbicli login --use-device-code'
Error: Authentication Error "invalid_resource":

AADSTS500011: The resource principal named https://analysis.windows.net/powerbi/api was not found in the tenant named kangbaolai. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: d7bf1ff8-faeb-4619-8650-5c193e9de200
Correlation ID: ddc53bee-8339-4f30-b6b7-f74431901e72
Timestamp: 2022-09-05 00:05:46Z
```

The login endpoint 'https://login.chinacloudapi.cn/common/oauth2/v2.0/authorize' looks correct, but resource uri ' https://analysis.windows.net/powerbi/api' seems still global cloud.

Scope should be "https://analysis.chinacloudapi.cn/powerbi/api/.default" per [this doc](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers-national-clouds).

**Comment by liprec** [comment]
I just push a new version that uses the correct audience urls. Please let me know if it is working for you now.

**Comment by kai-w-wang** [comment]
I passed login step this time, got failure on query of workspace/report:

```
C:\>pbicli workspace list --verbose
Shows details of the Power BI workspace: undefined
Check if stored token is not expired
Execute REST [GET] call to https://app.powerbi.cn/v1.0/myorg/groups
SyntaxError: Unexpected token u in JSON at position 0
```

**Comment by liprec** [comment]
Strange response as it then looks like the API is giving a different result as the global one (what I do not expect).
Just to be sure that the basics are setup correctly: is the SP correctly set regarding Power BI scopes? And that the SP does have access to the Power BI tenant?
And does the API call (`https://app.powerbi.cn/v1.0/myorg/groups`) work if you try it manually?

**Comment by liprec** [comment]
Closed due to age
